config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'home/index'
  get ':id', to: 'users#show', as: 'profile'

  resources :task_lists do
    member do
      post 'favorite'
      delete 'unfavorite'
    end
    resources :tasks do 
      member do
        post 'done'
        delete 'undone'
      end
    end
  end

  devise_for :users

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_list
  has_one :user, through: :task_list
  validates :name, presence: true

  def done_by? user
    user.done_tasks.include?(self)
  end
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  belongs_to :user
  has_many :user_favorite_task_lists
  has_many :favorited_by, through: :user_favorite_task_lists, source: :user
  has_many :tasks
  
  validates :user, presence: true
  validates :name, presence: true
  
  scope :publics, -> { where(public: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  friendly_id :name, use: :slugged

  has_many :task_lists
  has_many :user_favorite_task_lists
  has_many :favorite_task_lists, through: :user_favorite_task_lists, source: :task_list

  has_many :user_done_tasks
  has_many :done_tasks, through: :user_done_tasks, source: :task

  validates_presence_of :name, :slug
  validates_uniqueness_of :slug

  def public_task_lists
    task_lists.publics
  end

  def favorites task_list
    self.user_favorite_task_lists.create(task_list_id: task_list.id)
  end

  def unfavorites task_list
    self.user_favorite_task_lists.find_by(task_list_id: task_list.id).destroy
  end

  def avatar_url
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

  def completes task
    self.user_done_tasks.create(task_id: task.id)
  end

  def uncompletes task
    self.user_done_tasks.find_by(task_id: task.id).destroy
  end
end

app/models/user_done_task.rb
class UserDoneTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/models/user_favorite_task_list.rb
class UserFavoriteTaskList < ActiveRecord::Base
  belongs_to :user
  belongs_to :task_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  respond_to :html, :js

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  layout :layout_by_resource   

  private

  def layout_by_resource
    if devise_controller?
      "authentication"
    else
      "application"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push  :name, :slug
    devise_parameter_sanitizer.for(:account_update).push  :name, :slug
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @task_lists = current_user.task_lists
    @favorite_task_lists = current_user.favorite_task_lists 
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :update, :destroy, :favorite, :unfavorite]
  before_action :authenticate_user!
  before_action :validate_hack, only: [:update, :destroy]

  def create
    @task_list = task_list_scope.build(task_list_params)
    @task_list.save
    redirect_to profile_path current_user
  end

  def show
  end

  def update
    @task_list.update(task_list_params)
    render :update
  end

  def destroy
    @task_list.destroy
    @totalTaskLists = task_list_scope.reload.size
  end

  def favorite
    current_user.favorites @task_list
    render :update
  end

  def unfavorite
    current_user.unfavorites @task_list
    @totalFavoriteTaskLists = current_user.favorite_task_lists.reload.size
  end

  private

  def task_list_scope
    current_user.task_lists
  end

  def validate_hack
    raise "This task list not belongs to you!" if @task_list.user != current_user
  end

  def set_task_list
    @task_list = TaskList.find(params[:id])
  end

  def task_list_params
    params.require(:task_list).permit(:name, :public)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task_list, only: [:create, :update, :destroy]
  
  before_action :set_task, only: [:update, :destroy, :done, :undone]
  
  before_action :validate_hack, only: [:create, :update, :destroy]

  before_action :authenticate_user!

  def create
    @task = @task_list.tasks.build(task_params)
    @task.save
  end

  def update
    @task.update(task_params)
  end

  def destroy
    @task.destroy
  end

  def done
    current_user.completes @task
    render :update
  end

  def undone
    current_user.uncompletes @task
    render :update
  end

  private

  def validate_hack
    raise "This task list not belongs to you!" if @task_list.user != current_user
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def set_task_list
    @task_list = TaskList.find(params[:task_list_id])
  end

  def task_params
    params.require(:task).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show
  before_action :authenticate_user!

  def show
    @task_lists = is_profile_of_current_user? ? @user.task_lists : @user.public_task_lists
    @favorite_task_lists = @user.favorite_task_lists if is_profile_of_current_user?
    respond_with @user
  end

  private 

  def is_profile_of_current_user?
    current_user == @user
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user, size=48)
    "#{user.avatar_url}?s=#{size}&d=mm"
  end

  def current_user?(user)
    user and user.id == current_user.id
  end
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
          data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Easy Tasks', root_path, class: "navbar-brand" %>
    </div>

    
    <div class="collapse navbar-collapse" id="navbar">
    
      <% if user_signed_in? %>
       <!--  <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
        </form> -->
        
        <ul class="nav navbar-nav navbar-right">
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-target="menu" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag avatar(current_user, 28), class: "img-circle" %> 
            <span class="caret"></span>
            </a>
            <ul id="menu" class="dropdown-menu">
              <li>
                <%= link_to profile_path current_user do %>
                  <%= fa_icon "user" %> Profile
                <% end %>
              </li>
              <li role="separator" class="divider"></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %>
                  <%= fa_icon "sign-out" %> Logout
              <% end %>
              </li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<%= render "/users/profile" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Easytasks</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'nav' %>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Easytasks</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style> html, body {height: 100%;} </style> </head>
<body class="authentication gradient vertical-align">

<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="brand">Easy Tasks</h1>
    <div class="panel">
      <%= yield %>
    </div>
  </div>
</div>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/task_lists/_favorite_link.html.erb
<% if task_list.favorited_by.include?(current_user) %>
            
  <%= link_to unfavorite_task_list_path(task_list), class: "favorite", remote: true, method: :delete do %>
    <%= fa_icon "favorite" %>
  <% end %>

<% else %>
  
  <%= link_to favorite_task_list_path(task_list), class: "unfavorite", remote: true, method: :post do %>
    <%= fa_icon "unfavorite" %>
  <% end %>
    
<% end %>

app/views/task_lists/_form.html.erb
<a href="#" data-target="#new-task-modal" data-toggle="modal" class="action-link"><%= fa_icon "plus-circle" %> New Task List
</a>

<div class="modal fade" tabindex="-1" autofocus="true" role="dialog" id="new-task-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= simple_form_for task_list, html: { id: "new-task-form" } do |f| %>
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Task List</h4>
      </div>
      
      <div class="modal-body">
        <div class="input-group">
          <span class="input-group-addon">
            <%= fa_icon 'th-list' %>
          </span>
          <%= f.input :name, label: false, placeholder: "Task List Name" %>
        </div>
        <%= f.input :public, as: :boolean %>
        
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/task_lists/_form_inline.html.erb
<%= simple_form_for task_list, html: {class: "form-inline"}, remote: true do |f| %>    
    <div class="input-group">
      <%= f.input :name, label: false, placeholder: "Task List Name" %>
      
      <div class="input-group-btn">
        <%= f.button :button, class: "btn-primary " do %>
          <%= fa_icon "check" %>
        <% end %>
      </div>  
    </div>
<% end %>

app/views/task_lists/_form_modal.html.erb
<a href="#" data-target="#new-task-modal" data-toggle="modal" class="action-link"><%= fa_icon "plus-circle" %> New Task List
</a>

<div class="modal fade" tabindex="-1" autofocus="true" role="dialog" id="new-task-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= simple_form_for task_list do |f| %>
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Task List</h4>
      </div>
      
      <div class="modal-body">
        <div class="input-group">
          <span class="input-group-addon">
            <%= fa_icon 'th-list' %>
          </span>
          <%= f.input :name, label: false, placeholder: "Task List Name" %>
        </div>
        <%= f.input :public, as: :boolean %>
        
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/task_lists/_index.html.erb
<section id="task-lists-header">
  <h1 class="inline"><%= title %></h1>   

  <% if current_user? @user %>
    <%= render "/task_lists/form_modal", task_list: TaskList.new %>
  <% end %>
</section>

<section id="task-lists" class="panel-group">
  <div class="panel panel-default collection task-lists">
  
  <% task_lists.each do |task_list| %>

    <div data-task-list="<%= task_list.id %>">

      <div class="panel-heading task-list-info item">
        <%= render "/task_lists/task_list", task_list: task_list %>
      </div>

      <div id="task-list-<%= task_list.id %>-content" class="panel-collapse collapse">
        <div class="panel-body">
          <%= render "/tasks/index", task_list: task_list %>
        </div>
      </div>

    </div>
  <% end %>
  </div>
</section>

app/views/task_lists/_public_link.html.erb
<% if task_list.public %>
              
  <%= link_to task_list_path(task_list, task_list: {public: false}),remote: true, method: :put, class: "public" do %>
    <%= fa_icon "public" %>
  <% end %>
    
<% else %>
    
  <%= link_to task_list_path(task_list, task_list: {public: true}), remote: true, method: :put, class: "private" do %>
    <%= fa_icon "private" %>
  <% end %>

<% end %>

app/views/task_lists/_task_list.html.erb
  <div class="action-status inline">
    <% if current_user? task_list.user %>
      <%= render "/task_lists/public_link", task_list: task_list %>
    <% else %>
      <%= render "/task_lists/favorite_link", task_list: task_list %>
    <% end %>
  </div>
  
  <a class=" collapsed action-link" data-toggle="collapse" data-parent="#task-lists" href="#task-list-<%= task_list.id %>-content">
    <%= task_list.name %>
  </a>
  
  <% if current_user? task_list.user %>
    <div class="edit-form inline hidden">
      <%= render "/task_lists/form_inline", task_list: task_list %>
    </div>
    
    <a href="#" class="edit-btn" onclick="taskLists.edit(<%= task_list.id %>)">
      <%= fa_icon 'edit' %>
    </a>
  <% end %>
  
<%= link_to '', task_list_path(task_list), remote: true, method: :delete, class: "delete" if current_user? task_list.user %>

app/views/task_lists/destroy.js.erb
taskLists.remove(<%= @task_list.id %>);
profile.taskLists.setTotal(<%= @totalTaskLists %>);

app/views/task_lists/unfavorite.js.erb
if ($('.user-profile').length) {
  taskLists.remove(<%= @task_list.id %>);
  profile.favoriteTaskLists.setTotal(<%= @totalFavoriteTaskLists %>);
} else {
  taskLists.update(<%= @task_list.id %>).to('<%=j render partial: 'task_list', locals: {task_list: @task_list} %>');
}

app/views/task_lists/update.js.erb
taskLists.update(<%= @task_list.id %>).to('<%=j render partial: 'task_list', locals: {task_list: @task_list} %>')

app/views/tasks/_form.html.erb
<%= simple_form_for [task_list, task], remote: true do |f| %>
<div class="input-group">
  <div class="input-group-addon">
    <%= fa_icon "chevron-down" %>
  </div>
  <%= f.input :name, label: false, placeholder: "New Task" %>

  <div class="input-group-btn">
    <%= f.button :button, class: "new-task btn-primary " do %>
      <%= fa_icon "check" %>
    <% end %>
  </div>
</div>
<% end %> 

app/views/tasks/_index.html.erb
<section id="task-list-<%= task_list.id %>-tasks">
  <%= render "/tasks/form", task_list: task_list, task: Task.new if current_user? task_list.user %>

  <% if task_list.tasks.empty? %>
    <div class="alert alert-warning alert-empty-list">
      <%= fa_icon "exclamation-circle" %> No Tasks found
    </div>
  <% end %>

  <ul class="tasks collection">        
    <% task_list.tasks.each do |task| %>
      <%= render "/tasks/task", task: task %>
    <% end %>
  </ul>
</section>

app/views/tasks/_task.html.erb
<li data-task="<%= task.id %>" class="item <%= 'done' if task.done_by? current_user %>">
<% if task.done_by? current_user %>
  <%= link_to undone_task_list_task_path(task.task_list, task), remote: true, method: :delete do %>
    <%= task.name %>
  <% end %>
<% else %>
  <%= link_to done_task_list_task_path(task.task_list, task), remote: true, method: :post do %>
    <%= task.name %>
  <% end %>
<% end %>
<%= link_to '', task_list_task_path(task.task_list, task), remote: true, method: :delete, class: "delete" if current_user?(task.user) %>      
</li>
  

app/views/tasks/create.js.erb
var $scope = $('#task-list-<%= @task_list.id %>-tasks');

$scope.find('.alert-empty-list').hide();
$scope.find('.tasks').prepend('<%=j render partial: 'task', locals: {task: @task} %>');
$scope.find('#task_name').val('');

app/views/tasks/destroy.js.erb
var $scope = $('#task-list-<%= @task.task_list.id %>-tasks');
$scope
  .find(".item[data-task=<%= @task.id %>]")
  .remove();

app/views/tasks/update.js.erb
$('[data-task="<%= @task.id %>"]').replaceWith('<%=j render partial: 'task', locals: {task: @task} %>')

app/views/users/_avatar.html.erb
<%= image_tag avatar(user, size), class: "img-circle", widh: size, height: size, alt: "#{user.slug}_avatar" %>

app/views/users/_dashboard.html.erb
<section id="user-dashboard" class="header gradient text-center">

  <%= render '/users/avatar', user: @user, size: 100 %>

  <h3> <%= @user.name %> </h3> 
  <p> <%= @user.email %> </p>
  
  <h4 class="info-badge"> 
    <a href="#taskListsTab" data-toggle="tab">
    <%= fa_icon "th-list" %> task lists: 
    <span class="total-task-lists">
      <%= @task_lists.size %> 
    </span>
    </a>
  </h4>
  
  <% if current_user? @user %>
    <h4 class="info-badge"> 
      <a href="#favoritesTab" data-toggle="tab">
      <%= fa_icon "heart" %> favorites: 
      <span class="total-favorite-task-lists">				
      	<%= @user.favorite_task_lists.size %> 
      </span>
      </a>
    </h4>
  <% end %>

</section>

app/views/users/_profile.html.erb
<%= render '/users/dashboard' %>

<section id="user-task-lists" class="container <%= 'user-profile' if current_user? @user %> ">
      
    <div class="tab-content">
    
      <div class="tab-pane fade in active" id="taskListsTab">
        <%= render '/task_lists/index', title: "My Task Lists", task_lists: @task_lists %>
      </div>
      
      <% if current_user? @user %>
      <div class="tab-pane fade" id="favoritesTab">
        <%= render "/task_lists/index", title: "Favorite Task Lists", task_lists: @favorite_task_lists %>
      </div>
      <% end %>
    </div>

</section>

app/views/users/show.html.erb
<%= render "profile" %>